---
- name: Execute commands
  hosts: all
  become: yes

  tasks:

    - name: Download nodesource setup script
      command: curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh
    - name: Make the setup script executable
      command: chmod +x nodesource_setup.sh
    - name: Execute the setup script
      command: bash nodesource_setup.sh
    - name: Execute the setup script
      command: apt-get install nodejs -y