---
- name: Update Debian systems
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Install the package "vim
      ansible.builtin.apt:
        name: vim

    - name: Install the package "zabbix-agent"
      ansible.builtin.apt:
        name: zabbix-agent

    - name: Install the package "git
      ansible.builtin.apt:
        name: git

    - name: Echo IP address
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 172.30.30.3'

    - name: Clone repository
      git:
        repo: https://gitlab.thebull.ru/Kuznetsov/magicmirrorqr.git
        dest: /home/rock/electron_qr
        version: master

    - name: Run npm install
      command: npm install
      args:
        chdir: /home/rock/electron_qr/magicmirrorqr

