---
- name: Update Debian systems
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Install the package "vim
      ansible.builtin.apt:
        name: vim

    - name: Install the package "zabbix-agent"
      ansible.builtin.apt:
        name: zabbix-agent

