# for arm bian apt update cache not available
---
- name: Update systems
  hosts: all
  become: yes
  tasks:

    - name: Execute the setup script
      command: apt upgrade -y

    - name: Install the package "vim
      ansible.builtin.apt:
        name: vim

    - name: Install the package "zabbix-agent"
      ansible.builtin.apt:
        name: zabbix-agent

    - name: Install the package "git"
      ansible.builtin.apt:
        name: git

    - name: Install the package "gparted"
      ansible.builtin.apt:
        name: gparted

    - name: Install the package "pm2"
      ansible.builtin.apt:
        name: pm2

    - name: Echo IP address
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 172.30.30.3'

    - name: Download nodesource setup script
      command: curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh

    - name: Make the setup script executable
      command: chmod +x nodesource_setup.sh

    - name: Execute the setup script
      command: bash nodesource_setup.sh

    - name: Execute the setup script
      command: apt-get install nodejs -y

    - name: Clone repository
      git:
        repo: https://gitlab.thebull.ru/Kuznetsov/magicmirrorqr.git
        dest: /home/rock/electron_qr
        version: master

    - name: Run npm install
      command: npm install
      args:
        chdir: /home/rock/electron_qr

